# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- recent_posts
- tagcloud
- archive

# Miscellaneous
google_analytics: 
favicon: /favicon.ico
twitter: 
google_plus:
fb_admins:
fb_app_id: